name: Weather Report
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Weather
        run: |
          CITY="Prague"
          WEATHER=$(curl -s "wttr.in/$CITY?format=3")
          echo "Weather in $CITY: $WEATHER"

          echo "## $CITY Weather" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**$WEATHER**" >> $$GITHUB_STEP_SUMMARY
